### ISSUE TITLE
changes in quizzes 

### ISSUE THREAD

**Issue by RCODI** [HackPurdue/purdue-ironhacks#72]
HTML and CSS - https://purdue.ca1.qualtrics.com/jfe/form/SV_0l9UUOmgB2TCZ1P

Bootstrap - https://purdue.ca1.qualtrics.com/jfe/form/SV_ai47Laj9EM1n433

Javascript and jQuery - https://purdue.ca1.qualtrics.com/jfe/form/SV_1Xkpq23Qu5j7P01

Google Map API - https://purdue.ca1.qualtrics.com/jfe/form/SV_eEe3JnzCkS2ppnn

D3.js - https://purdue.ca1.qualtrics.com/jfe/form/SV_0ep4CDeW4BYTckR

**Comment by IonicaBizau** [comment]
Actually all of them

**Comment by RCODI** [comment]
@IonicaBizau , yes Johnny, we purposely made them in spanish as the students who participate in our university hack this semester with be from south america and their main language is spanish :-)
