### ISSUE TITLE
pre-survey change 

### ISSUE THREAD

**Issue by RCODI** [HackPurdue/purdue-ironhacks#73]
https://purdue.ca1.qualtrics.com/jfe/form/SV_23GkqPCNMdqsdo1

**Comment by IonicaBizau** [comment]
The survey expired

**Comment by RCODI** [comment]
@IonicaBizau . Here is the link to the non-expired survey.https://purdue.ca1.qualtrics.com/jfe/form/SV_23GkqPCNMdqsdo1. Thanks for the heads up Johnny :-)
